<?php

namespace Egzakt\MailChimpBundle\Entity;

use Egzakt\Backend\CoreBundle\Lib\BaseEntityRepository;

/**
 * SubscriberListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberListRepository extends BaseEntityRepository
{
}